--- /home/ec2-user/TEST/pgbouncer/Makefile	2015-12-29 17:32:40.174622100 -0500
+++ ./Makefile	2015-12-29 17:30:59.946064408 -0500
@@ -18,12 +18,15 @@ pgbouncer_SOURCES = \
 	src/sbuf.c \
 	src/server.c \
 	src/stats.c \
 	src/system.c \
 	src/takeover.c \
 	src/util.c \
+        src/pycall.c \
+        src/route_connection.c \
+        src/rewrite_query.c \
 	src/varcache.c \
 	include/admin.h \
 	include/bouncer.h \
 	include/client.h \
 	include/dnslookup.h \
 	include/hba.h \
@@ -37,22 +40,26 @@ pgbouncer_SOURCES = \
 	include/sbuf.h \
 	include/server.h \
 	include/stats.h \
 	include/system.h \
 	include/takeover.h \
 	include/util.h \
+        include/pycall.h \
+        include/route_connection.h \
+        include/rewrite_query.h \
 	include/varcache.h
 
-pgbouncer_CPPFLAGS = -Iinclude $(CARES_CFLAGS) $(TLS_CPPFLAGS)
+python_CPPFLAGS = -I/usr/include/python2.7 -I/usr/include/python2.7 
+pgbouncer_CPPFLAGS = -Iinclude $(CARES_CFLAGS) $(TLS_CPPFLAGS) $(python_CPPFLAGS)
 
 # include libusual sources directly
 AM_FEATURES = libusual
 pgbouncer_EMBED_LIBUSUAL = 1
 
 # docs to install as-is
-dist_doc_DATA = README.rst NEWS.rst etc/pgbouncer.ini etc/userlist.txt
+dist_doc_DATA = README.md README.rst NEWS.rst etc/pgbouncer.ini etc/userlist.txt
 
 DISTCLEANFILES = config.mak config.status lib/usual/config.h config.log
 
 DIST_SUBDIRS = doc test
 dist_man_MANS = doc/pgbouncer.1 doc/pgbouncer.5
 
@@ -81,13 +88,14 @@ CPPFLAGS += -DDBGVER="\"compiled by <$${
 endif
 
 #
 # win32
 #
 
-pgbouncer_LDFLAGS := $(TLS_LDFLAGS)
+python_LDFLAGS = -lpthread -ldl -lutil -lm -lpython2.7 -Xlinker -export-dynamic
+pgbouncer_LDFLAGS := $(TLS_LDFLAGS) $(python_LDFLAGS)
 pgbouncer_LDADD := $(CARES_LIBS) $(TLS_LIBS) $(LIBS)
 LIBS :=
 
 EXTRA_pgbouncer_SOURCES = win32/win32support.c win32/win32support.h
 EXTRA_PROGRAMS = pgbevent
 ifeq ($(PORTNAME),win32)
