---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adaptivepgbouncer
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - rbac.authorization.k8s.io
  - extensions
  - apps
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  - pods
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adaptivepgbouncer
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adaptivepgbouncer
  namespace: default
subjects:
- kind: ServiceAccount
  name: adaptivepgbouncer
  namespace: default
roleRef:
  kind: ClusterRole
  name: adaptivepgbouncer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: default
  labels:
    app: pgbouncer
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 10
  selector:
    matchLabels:
      app: pgbouncer
  template:
    metadata:
      labels:
        app: pgbouncer
    spec:
      nodeSelector:
        karpenter.sh/provisioner-name: default
      serviceAccountName: adaptivepgbouncer
      containers:
        - name: pgbouncer
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-west-2.amazonaws.com/pgbouncer:1.15.0amzn2.aarch64
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: 512m
              memory: 512Mi
            limits:
              cpu: 512m
              memory: 512Mi
          envFrom:
            - secretRef:
               name: pgbouncer
          env:
            - name: default_pool_size
              value: "20"
            - name: log_connections
              value: "1"
            - name: log_disconnections
              value: "1"
            - name: log_pooler_errors
              value: "1"
            - name: log_stats
              value: "1"
            - name: routing_rules_py_module_file 
              value: "/home/pgbouncer/routing_rules.py"
            - name: PGB_LISTEN_PORT
              value: "5432"
            - name: PGB_LISTEN_ADDR
              value: "0.0.0.0"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            tcpSocket:
              port: 5432
            periodSeconds: 60
          lifecycle:
            preStop:
              exec:
                # Allow existing queries clients to complete within 120 seconds
                command: ["/bin/sh", "-c", "killall -INT pgbouncer && sleep 120"]
